### ISSUE TITLE
Add information about the "original period" corresponding to the selected representative

### ISSUE THREAD

**Issue by DillonJ** [TulipaEnergy/TulipaClustering.jl#55]
### Description

Hi from the Spine project @abelsiqueira @datejada and, in particular, [SpineOpt](https://github.com/spine-tools/SpineOpt.jl).

I have written a script to run the clustering algorithm on a SpineOpt datastore and it works very nicely. I'm now looking at the implementation in SpineOpt. However, I'm struggling to make sense of the custing_result data. I can see the weights from original periods to representative periods but I can't see where it tells me the actual representative periods which have been identified. For example, if I asked for 12 representative periods, I can see how each original period maps to periods 1 through 12... but I don't see where it tells me what original period representative period 1 relates to.

Perhaps I have misunderstood something, but I would appreciate some guidance.

Thanks in advance!

**Comment by datejada** [comment]
**Action**: Include an example of using the package from the input data and getting the results, including their interpretation.

**Comment by DillonJ** [comment]
Thanks for that @datejada 

Say I have requested 12 representative periods, where in the result does it tell you the correspondence between the representative periods and the original periods? I.e. what original period does rp1 correspond to.

I believe rp_matrix tells us for each original period, the representative period it is represented by - but how do we get the information about the representative periods themselves and the periods of time they relate to in the original data?

Sorry if I have missed something really simple!

**Comment by DillonJ** [comment]
OK, I see now... you are regenerating the timeseries data so that that time series data itself is representative.

In SpineOpt we don't touch the timeseries data and instead store the mapping the timeslices. It would indeed be useful to have as an output the rep-period to original period mapping so we can implement this in Spine.

Thanks again for all the help and explanations

**Comment by datejada** [comment]
**Action**: Add information about the original period in which the representative was selected. For example, if we have days as the period of the representatives and we want two representatives, then we would like to know which original period corresponds to each representative (e.g., representative 1 is day 23 and representative 2 is day 304 in the original data). This information will only be available if the method is k-medoids (for k-means, maybe `nothing` is the suitable output). Please check where is the best place to allocate this information in the `clustering_result` structure (maybe in the `auxiliary_data` information).

Happy coding!
